Fix #17219 Corrected the Fraction output logic
oppia/guppy pull request #10
Opened 2024-03-01 19:29 UTC by HardikGoyal2003

## Overview

1. This PR fixes or fixes part of  [#17219](https://github.com/oppia/oppia/issues/17219).
2. This PR does the following: Updates the output for fractions in Guppy.

## Essential Checklist

- [x] The **PR title** starts with "Fix #bugnum: " or "Fix part of #bugnum: ...", followed by a short, clear summary of the changes.
- [x] I have followed the build process and "verifying your changes" section mentioned in the [readme file](https://github.com/oppia/guppy/blob/master/README.md).
- [x] I have followed the [instructions for making a code change](https://github.com/oppia/oppia/wiki/Make-a-pull-request).
- [x] I have assigned the correct reviewers to this PR (or will leave a comment with the phrase "@{{reviewer_username}} PTAL" if I don't have permissions to assign reviewers directly).
- [x] The linter/Karma presubmit checks pass on my local machine, and my PR follows the [coding style guide](https://github.com/oppia/oppia/wiki/Coding-style-guide)).
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)

## Proof that changes are correct

[Screencast from 02-03-24 12:21:14 AM IST.webm](https://github.com/oppia/guppy/assets/135348086/b39250c9-961d-4fd4-9065-0f8d5f02e772)

## PR Pointers

- Never force push! If you do, your PR will be closed.
- To reply to reviewers, follow these instructions: https://github.com/oppia/oppia/wiki/Make-a-pull-request#step-5-address-review-comments-until-all-reviewers-approve
- Some e2e tests are flaky, and can fail for reasons unrelated to your PR. We are working on fixing this, but in the meantime, if you need to restart the tests, please check the ["If your build fails" wiki page](https://github.com/oppia/oppia/wiki/If-CI-checks-fail-on-your-PR).
- See the [Code Owner's wiki page](https://github.com/oppia/oppia/wiki/Oppia's-code-owners-and-checks-to-be-carried-out-by-developers) for what code owners will expect.

2024-03-01 19:30 UTC, HardikGoyal2003 commented
@seanlip PTAL! Thanks!

2024-03-03 18:44 UTC, seanlip requested changes
@HardikGoyal2003 Which code am I actually supposed to review here? I don't see the source file(s) from which all these builds were generated, and I also don't understand why this has changed so much from the master branch. Could you please explain?

2024-03-03 23:02 UTC, HardikGoyal2003 commented
> @HardikGoyal2003 Which code am I actually supposed to review here? I don't see the source file(s) from which all these builds were generated, and I also don't understand why this has changed so much from the master branch. Could you please explain?

@seanlip I analysed and what I found is:
- on running ``$ npm test`` it creates the hash changes in all files in coverage folder which is just to test and check test coverage.
- Using build command doesn't make any changes in min.js file, hence we need to do it manually.
- if we are changing the source files and keeping min.js file unchanged then no changes will be reflected on localhost, therefore localhost depends on min.js file.
- if we change src file then run build command other files also gets updated but min.js file is constant.

Thanks!

2024-03-03 23:12 UTC, HardikGoyal2003 commented
@seanlip I have reverted the last commit and now test command has not been run but build command has been run and min.js has been edited manually. Thanks

2024-03-04 17:13 UTC, seanlip commented
@HardikGoyal2003 This is a concern IMO. We need a standard build process that also updates the min.js file, and this should be documented in the PR template etc. What should that process be? What does the guppy project itself usually use?

2026-04-26 14:46 UTC, closed without merging