min.js updated
oppia/guppy pull request #7
Opened 2024-02-20 13:59 UTC by HardikGoyal2003

Updated min.js file

2024-02-20 14:01 UTC, HardikGoyal2003 commented
@seanlip PTAL! In the last PR min.js file was broken due to some external code. Now this has been updated and only certain part has been changed and no formating has been touched. Thanks!

2024-02-22 18:41 UTC, seanlip commented
Please provide video proof of correctness in this PR, update the title and description to give sufficient detail, and explain the steps/commands you used to minify the file (and what was wrong before). Thanks.

(This context is important for reviewers. Please make sure other PRs are similarly clear, otherwise reviewers will just return the PR to you and ask for more details, which isn't a great use of time.)

2024-02-22 18:51 UTC, HardikGoyal2003 commented
@seanlip PTAL! Thanks!

2024-02-22 18:55 UTC, seanlip requested changes
Still not reviewing this. Check your PR for correctness from a reviewer's perspective and make sure that all parts of it are correct and that all my points in the previous comment were fully addressed.

2024-02-22 19:43 UTC, HardikGoyal2003 commented
> Still not reviewing this. Check your PR for correctness from a reviewer's perspective and make sure that all parts of it are correct and that all my points in the previous comment were fully addressed.

@seanlip  As this [comment](https://github.com/oppia/guppy/pull/6#issuecomment-1960059133) suggests I did build and testing, but I ran command for both the currently active version and the local version after my changes, to check differences in both version, output for both are:

## Current active version
![image](https://github.com/oppia/guppy/assets/135348086/32d1e616-5c6d-4ccc-8da1-b1dacba3011f)
![image](https://github.com/oppia/guppy/assets/135348086/f332857f-82de-4e93-82eb-dd076f6d37a8)

## Local version after my changes
![image](https://github.com/oppia/guppy/assets/135348086/12b4bddb-5365-4c03-b574-5b6bf789b399)
![image](https://github.com/oppia/guppy/assets/135348086/4f1e7026-7e7e-4f84-a018-b2d446031db7)

## Analysis

As output for both shows there no change in min.js file but the other file is changing a lot, should we add these changes or revert these changes?

2024-02-24 16:33 UTC, seanlip commented
Thanks @HardikGoyal2003. Please add these changes and include an update to the README or the PR template to run this command and include the changes in every PR.

2024-02-24 16:43 UTC, HardikGoyal2003 commented
@seanlip If I'm getting this correct, you are talking about the Guppy ReadMe file, and this PR's template as if we don't have any PR template for the Guppy repo??

2024-02-24 16:45 UTC, seanlip commented
The first is correct, and for the second I am suggesting we add a Guppy repo PR template (the same way as we do in Oppia) with this information.

For that PR template you can adapt the general one from Oppia as well.

2024-02-24 18:00 UTC, HardikGoyal2003 commented
@seanlip I was editing the Readme file, and I thought to take a look at other files, this is how they look after the build,
so I feel adding build changes will not be a good idea.

2024-02-24 18:19 UTC, seanlip commented
Thanks. Before the build, were there errors? If not, what changed from before the build to after?

Wondering if the issue is with the build or with our past changes.

2024-02-24 18:44 UTC, HardikGoyal2003 commented
@seanlip There were no errors before the build, as I have shown below
[Screencast from 25-02-24 12:00:46 AM IST.webm](https://github.com/oppia/guppy/assets/135348086/fc069a0b-cee7-4e6c-bf76-4adaefd2cd4e)

There are many changes including function changes, module changes, and many more changes I can't understand.

2024-02-25 02:40 UTC, seanlip commented
Ah, sorry, you did say that above. Thanks for checking.

Can you checkout commit 1759992a3885cb99d3ead04241f318a074c9f963 which is where we originally forked the repo, and then try building that? If it works fine then the problem is something we did along the way, so maybe checkout the next few commits [here](https://github.com/oppia/guppy/commits/master/) and see where the errors first occur. At that point we can decide whether to fix them or to file an issue and leave it be for now, but let's do a little more investigation to find the root cause of this since we ought to standardize our build instructions. Thanks!

2024-02-25 20:15 UTC, HardikGoyal2003 commented
@seanlip I tried building using the commit you mentioned and it was also showing errors, then I analyzed more, and it was all Eslint errors as without usage you can't find logic errors. So we can add changes but I feel we should do this in 2 PRs, 
1. Changes I made 
2. Build changes

so that we will be assured whether the build is breaking the codebase or not.

2024-02-26 17:42 UTC, seanlip commented
Yes, seems reasonable. Can you do another PR fixing the build changes first (just on the master branch), then we can merge that, and then apply the build process to this PR and all other PRs moving forward?

2024-02-26 21:00 UTC, HardikGoyal2003 commented
@seanlip I have opened a [PR](https://github.com/oppia/guppy/pull/9) with build file changes on the master branch, let's see after merging this PR. Thanks!

2024-03-01 19:02 UTC, closed without merging